<?php

namespace app\modules\page\models;

use Yii;

/**
 * This is the model class for table "page_city_content".
 *
 * @property int $id
 * @property int $city_id Город
 * @property int $page_id Страница
 * @property string $content Содержание
 * @property string $content_seo_1 SEO 1
 * @property string $content_seo_2 SEO 2
 *
 * @property City $city
 * @property Page $page
 */
class PageCityContent extends \app\models\PageCityContent {

    public static function Add($data) {

        if ($model = self::findOne(['city_id' => $data['city_id'], 'page_id' => $data['page_id']])):


            $model->title = $data['title'];
            $model->description = $data['description'];
            $model->header = $data['header'];
            $model->content = $data['content'];
            $model->content_seo_1 = $data['content_seo_1'];
            $model->content_seo_2 = $data['content_seo_2'];
            $model->cases = $data['cases'];

        else:
            $model = new self();

            $model->city_id = $data['city_id'];
            $model->page_id = $data['page_id'];
            $model->title = $data['title'];
            $model->description = $data['description'];
            $model->header = $data['header'];
            $model->content = $data['content'];
            $model->content_seo_1 = $data['content_seo_1'];
            $model->content_seo_2 = $data['content_seo_2'];
            $model->cases = $data['cases'];
        endif;

        $model->save();

    }

    public function beforeSave($insert)
    {
        $this->cases = $this->cases ? implode(',', $this->cases) : '';
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind() {

        $this->cases = explode(',', $this->cases);
        return parent::afterFind();
    }

    public function getCases()
    {
        return $this->cases;
    }

}
